config/routes.rb
Rails.application.routes.draw do
 root 'sims#index'

 resources :sims 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sim.rb
class Sim < ActiveRecord::Base
	validates :date, :title, :amount, presence: true

	def self.balance
		where("amount > ?",0).sum(:amount)

	end

	def self.debt
		where("amount < 0",0).sum(:amount)

	end

	def self.total 
		sum(:amount)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sims_controller.rb
class SimsController < ApplicationController
	def index
		@sims = Sim.all
		@balance=Sim.balance
		@debt=Sim.debt
		@total=Sim.total
	end

	def create
		@sim = Sim.create(sim_params)
		if @sim.valid?
			flash[:sucess]="New record has been created"
			redirect_to root_path
		else
		 	flash[:alert]="Woops! A element is missing!"
		 	redirect_to new_sim_path(params[:id])

		end
	end

	
	def edit
		@sim = Sim.find(params[:id])
	end

	def update
		@sim = Sim.find(params[:id])
		if @sim.update(sim_params)
			flash[:sucess]="Your record has been updated"
		   redirect_to root_path
		 else
		 	flash[:alert]="Woops! Looks like there has been an error!"
		   redirect_to edit_sim_path(params[:id])
		end
    end

    def destroy
	  @sim = Sim.find(params[:id])
	  @sim.destroy
	  flash[:sucess]= "A record has been deleted"
	  redirect_to root_path
	end

	def new
	end

	private

	def sim_params
		params.require(:sim).permit(:date, :title, :amount)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sims_helper.rb
module SimsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simaccount</title>
    <%= csrf_meta_tags %>
	<link href="https://fonts.googleapis.com/css?family=Dosis|Open+Sans:300,400,600" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id= "wrap">
      <%= render 'shared/nav' %>
        <div class="container">
          <%= render 'shared/flash_messages' %>
              <%= yield %> 
        </div>
    </div>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <% if message_type == "notice" %>
    <p class="alert alert-info alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= notice %></p>
  <% elsif message_type == "alert" %>
    <p class="alert alert-danger alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= alert %></p>
  <% else %>
    <div class="alert alert-<%= message_type %> alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= message %></div>
  <% end %>
<% end %>

app/views/shared/_nav.html.erb
<div class="navbar-header navbar-color">
  		<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	    <span class="sr-only">Toggle navigation</span>
	    <span class="icon-bar"></span>
	    <span class="icon-bar"></span>
	    <span class="icon-bar"></span>
	  	</button>
  		<a class="navbar-brand navcolor" href="/">Simple Accounting</a>
  		<ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'New Record', new_sim_path %></li>
    </ul>
 </div>

 

app/views/sims/edit.html.erb
<h1>Edit record</h1>
<%= simple_form_for @sim, method: :patch do |f| %>
  <%= f.input :date %>
  <%= f.input :title %>
  <%= f.input :amount %>
  <%= f.submit 'Create Record', class: 'btn btn-primary ' %>
<% end %>

app/views/sims/index.html.erb
<div class="container">
<h1>Balance:<%= @balance%></h1>
<h1>Debt:<%= @debt%></h1>
<h1>Total:<%= @total%></h1>
<table class ="table">
  <tr>
    <th>Data</th>
    <th>Title</th>
    <th>Amount</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>

  <% @sims.each do |sim| %>
  			<tr>
 				<td><%= sim.date %></td>
	 			<td><%= sim.title %></td>
				<td><%= sim.amount %></td>
				<td><%= link_to 'Edit', edit_sim_path(sim), class: 'btn btn-primary'%></td>
				<td><%= link_to 'Delete', sim_path(sim), method: :delete, class: 'btn btn-danger', data: {confirm: "Are you sure?"} %></td>
	 		</tr>
	
<% end %>

</table>
</div>

app/views/sims/new.html.erb
<%= simple_form_for Sim.new do |f| %>
  <%= f.input :date %>
  <%= f.input :title %>
  <%= f.input :amount %>
  <%= f.submit 'Create Record', class: 'btn btn-primary ' %>
<% end %>